// <auto-generated />
using System;
using BikeMate.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace BikeMate.Infrastructure.Migrations
{
    [DbContext(typeof(BikeMateDbContext))]
    partial class BikeMateDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("BikeMate.Core.Entities.AuditLog", b =>
                {
                    b.Property<int>("AuditId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("AuditId"));

                    b.Property<string>("ActionName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int?>("ActorUserId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("EntityId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("EntityName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("NewValuesJson")
                        .HasColumnType("text");

                    b.Property<string>("OldValuesJson")
                        .HasColumnType("text");

                    b.HasKey("AuditId");

                    b.HasIndex("ActorUserId");

                    b.ToTable("audit_logs", (string)null);
                });

            modelBuilder.Entity("BikeMate.Core.Entities.Client", b =>
                {
                    b.Property<int>("ClientId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ClientId"));

                    b.Property<DateTime?>("Birthdate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("MiddleName")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Sex")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.Property<string>("ValidIdImageUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.HasKey("ClientId");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("clients", (string)null);

                    b.HasData(
                        new
                        {
                            ClientId = 1,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UserId = 2
                        });
                });

            modelBuilder.Entity("BikeMate.Core.Entities.ClientAddress", b =>
                {
                    b.Property<int>("AddressId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("AddressId"));

                    b.Property<string>("AddressLine")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Barangay")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("City")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("ClientId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<bool>("IsDefault")
                        .HasColumnType("boolean");

                    b.Property<string>("Label")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<decimal?>("Latitude")
                        .HasPrecision(10, 8)
                        .HasColumnType("numeric(10,8)");

                    b.Property<decimal?>("Longitude")
                        .HasPrecision(11, 8)
                        .HasColumnType("numeric(11,8)");

                    b.Property<string>("PostalCode")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Province")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("AddressId");

                    b.HasIndex("ClientId");

                    b.ToTable("client_addresses", (string)null);
                });

            modelBuilder.Entity("BikeMate.Core.Entities.Conversation", b =>
                {
                    b.Property<int>("ConversationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ConversationId"));

                    b.Property<string>("ConversationType")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasDefaultValue("service_request");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime?>("LastMessageAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int?>("RequestId")
                        .HasColumnType("integer");

                    b.HasKey("ConversationId");

                    b.HasIndex("RequestId");

                    b.ToTable("conversations", (string)null);
                });

            modelBuilder.Entity("BikeMate.Core.Entities.ConversationParticipant", b =>
                {
                    b.Property<int>("ConversationId")
                        .HasColumnType("integer");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("JoinedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime?>("LastReadAt")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("ConversationId", "UserId");

                    b.HasIndex("UserId");

                    b.ToTable("conversation_participants", (string)null);
                });

            modelBuilder.Entity("BikeMate.Core.Entities.LiveLocation", b =>
                {
                    b.Property<int>("LiveLocationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("LiveLocationId"));

                    b.Property<decimal?>("AccuracyMeters")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<decimal>("Latitude")
                        .HasPrecision(10, 8)
                        .HasColumnType("numeric(10,8)");

                    b.Property<decimal>("Longitude")
                        .HasPrecision(11, 8)
                        .HasColumnType("numeric(11,8)");

                    b.Property<int?>("MechanicId")
                        .HasColumnType("integer");

                    b.Property<int?>("RequestId")
                        .HasColumnType("integer");

                    b.HasKey("LiveLocationId");

                    b.HasIndex("MechanicId");

                    b.HasIndex("RequestId");

                    b.ToTable("live_locations", (string)null);
                });

            modelBuilder.Entity("BikeMate.Core.Entities.Mechanic", b =>
                {
                    b.Property<int>("MechanicId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("MechanicId"));

                    b.Property<string>("AddressLine")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("AvailabilityStatus")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasDefaultValue("offline");

                    b.Property<decimal>("AverageRating")
                        .HasPrecision(3, 2)
                        .HasColumnType("numeric(3,2)");

                    b.Property<string>("Barangay")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Bio")
                        .HasColumnType("text");

                    b.Property<DateTime?>("Birthdate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("CertificationImageUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("City")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<decimal?>("CurrentLatitude")
                        .HasPrecision(10, 8)
                        .HasColumnType("numeric(10,8)");

                    b.Property<decimal?>("CurrentLongitude")
                        .HasPrecision(11, 8)
                        .HasColumnType("numeric(11,8)");

                    b.Property<bool>("IsVerified")
                        .HasColumnType("boolean");

                    b.Property<string>("MiddleName")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Province")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Sex")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<int>("TotalCompletedJobs")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.Property<string>("ValidIdImageUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int?>("YearsExperience")
                        .HasColumnType("integer");

                    b.Property<string>("ZipCode")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.HasKey("MechanicId");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("mechanics", (string)null);

                    b.HasData(
                        new
                        {
                            MechanicId = 1,
                            AvailabilityStatus = "online",
                            AverageRating = 0m,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsVerified = false,
                            TotalCompletedJobs = 0,
                            UserId = 3
                        });
                });

            modelBuilder.Entity("BikeMate.Core.Entities.MechanicAvailability", b =>
                {
                    b.Property<int>("AvailabilityId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("AvailabilityId"));

                    b.Property<int>("DayOfWeek")
                        .HasColumnType("integer");

                    b.Property<TimeSpan>("EndTime")
                        .HasColumnType("interval");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<int>("MechanicId")
                        .HasColumnType("integer");

                    b.Property<TimeSpan>("StartTime")
                        .HasColumnType("interval");

                    b.HasKey("AvailabilityId");

                    b.HasIndex("MechanicId");

                    b.ToTable("mechanic_availability", (string)null);
                });

            modelBuilder.Entity("BikeMate.Core.Entities.Message", b =>
                {
                    b.Property<int>("MessageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("MessageId"));

                    b.Property<string>("AttachmentUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int>("ConversationId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("MessageText")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("ReadAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("SenderUserId")
                        .HasColumnType("integer");

                    b.HasKey("MessageId");

                    b.HasIndex("ConversationId");

                    b.HasIndex("SenderUserId");

                    b.ToTable("messages", (string)null);
                });

            modelBuilder.Entity("BikeMate.Core.Entities.Motorcycle", b =>
                {
                    b.Property<int>("MotorcycleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("MotorcycleId"));

                    b.Property<string>("Brand")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("ClientId")
                        .HasColumnType("integer");

                    b.Property<string>("Color")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("EngineType")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("MotorcycleImageUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("PlateNumber")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int?>("YearModel")
                        .HasColumnType("integer");

                    b.HasKey("MotorcycleId");

                    b.HasIndex("ClientId");

                    b.ToTable("motorcycles", (string)null);
                });

            modelBuilder.Entity("BikeMate.Core.Entities.Notification", b =>
                {
                    b.Property<int>("NotificationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("NotificationId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("DataJson")
                        .HasColumnType("text");

                    b.Property<bool>("IsRead")
                        .HasColumnType("boolean");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("NotificationType")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("NotificationId");

                    b.HasIndex("UserId");

                    b.ToTable("notifications", (string)null);
                });

            modelBuilder.Entity("BikeMate.Core.Entities.OtpVerification", b =>
                {
                    b.Property<int>("OtpId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("OtpId"));

                    b.Property<int>("Attempts")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("ConsumedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("OtpHash")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Purpose")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasDefaultValue("email_verification");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("OtpId");

                    b.HasIndex("UserId");

                    b.ToTable("otp_verifications", (string)null);
                });

            modelBuilder.Entity("BikeMate.Core.Entities.PasswordResetToken", b =>
                {
                    b.Property<int>("TokenId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("TokenId"));

                    b.Property<DateTime?>("ConsumedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("TokenId");

                    b.HasIndex("UserId");

                    b.ToTable("password_reset_tokens", (string)null);
                });

            modelBuilder.Entity("BikeMate.Core.Entities.Payment", b =>
                {
                    b.Property<int>("PaymentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("PaymentId"));

                    b.Property<decimal>("Amount")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)");

                    b.Property<string>("CheckoutUrl")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<int>("ClientId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasDefaultValue("PHP");

                    b.Property<DateTime?>("PaidAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int?>("PaymentMethodId")
                        .HasColumnType("integer");

                    b.Property<int>("PaymentStatusId")
                        .HasColumnType("integer");

                    b.Property<string>("ProviderCheckoutSessionId")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("ProviderName")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasDefaultValue("paymongo");

                    b.Property<string>("ProviderPaymentId")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("ProviderReferenceNumber")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<int>("RequestId")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("PaymentId");

                    b.HasIndex("ClientId");

                    b.HasIndex("PaymentMethodId");

                    b.HasIndex("PaymentStatusId");

                    b.HasIndex("RequestId");

                    b.ToTable("payments", (string)null);
                });

            modelBuilder.Entity("BikeMate.Core.Entities.PaymentEvent", b =>
                {
                    b.Property<int>("PaymentEventId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("PaymentEventId"));

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("PayloadJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("PaymentId")
                        .HasColumnType("integer");

                    b.Property<string>("ProviderEventId")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<DateTime>("ReceivedAt")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("PaymentEventId");

                    b.HasIndex("PaymentId");

                    b.ToTable("payment_events", (string)null);
                });

            modelBuilder.Entity("BikeMate.Core.Entities.PaymentMethod", b =>
                {
                    b.Property<int>("PaymentMethodId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("PaymentMethodId"));

                    b.Property<string>("MethodName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("PaymentMethodId");

                    b.HasIndex("MethodName")
                        .IsUnique();

                    b.ToTable("payment_methods", (string)null);

                    b.HasData(
                        new
                        {
                            PaymentMethodId = 1,
                            MethodName = "gcash"
                        },
                        new
                        {
                            PaymentMethodId = 2,
                            MethodName = "maya"
                        },
                        new
                        {
                            PaymentMethodId = 3,
                            MethodName = "card"
                        },
                        new
                        {
                            PaymentMethodId = 4,
                            MethodName = "grab_pay"
                        },
                        new
                        {
                            PaymentMethodId = 5,
                            MethodName = "cash"
                        },
                        new
                        {
                            PaymentMethodId = 6,
                            MethodName = "bank_transfer"
                        });
                });

            modelBuilder.Entity("BikeMate.Core.Entities.PaymentStatus", b =>
                {
                    b.Property<int>("PaymentStatusId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("PaymentStatusId"));

                    b.Property<string>("StatusName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("PaymentStatusId");

                    b.HasIndex("StatusName")
                        .IsUnique();

                    b.ToTable("payment_statuses", (string)null);

                    b.HasData(
                        new
                        {
                            PaymentStatusId = 1,
                            StatusName = "unpaid"
                        },
                        new
                        {
                            PaymentStatusId = 2,
                            StatusName = "pending"
                        },
                        new
                        {
                            PaymentStatusId = 3,
                            StatusName = "paid"
                        },
                        new
                        {
                            PaymentStatusId = 4,
                            StatusName = "failed"
                        },
                        new
                        {
                            PaymentStatusId = 5,
                            StatusName = "cancelled"
                        },
                        new
                        {
                            PaymentStatusId = 6,
                            StatusName = "refunded"
                        });
                });

            modelBuilder.Entity("BikeMate.Core.Entities.Product", b =>
                {
                    b.Property<int>("ProductId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ProductId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<decimal>("Price")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)");

                    b.Property<string>("ProductDescription")
                        .HasColumnType("text");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<int>("ShopId")
                        .HasColumnType("integer");

                    b.Property<int>("StockQuantity")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("ProductId");

                    b.HasIndex("ShopId");

                    b.ToTable("products", (string)null);
                });

            modelBuilder.Entity("BikeMate.Core.Entities.ProductImage", b =>
                {
                    b.Property<int>("ProductImageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ProductImageId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int>("ProductId")
                        .HasColumnType("integer");

                    b.HasKey("ProductImageId");

                    b.HasIndex("ProductId");

                    b.ToTable("product_images", (string)null);
                });

            modelBuilder.Entity("BikeMate.Core.Entities.RequestMedia", b =>
                {
                    b.Property<int>("RequestMediaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("RequestMediaId"));

                    b.Property<string>("Caption")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("MediaType")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasDefaultValue("image");

                    b.Property<string>("MediaUrl")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int>("RequestId")
                        .HasColumnType("integer");

                    b.HasKey("RequestMediaId");

                    b.HasIndex("RequestId");

                    b.ToTable("request_media", (string)null);
                });

            modelBuilder.Entity("BikeMate.Core.Entities.RequestStatus", b =>
                {
                    b.Property<int>("StatusId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("StatusId"));

                    b.Property<string>("StatusName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("StatusId");

                    b.HasIndex("StatusName")
                        .IsUnique();

                    b.ToTable("request_statuses", (string)null);

                    b.HasData(
                        new
                        {
                            StatusId = 1,
                            StatusName = "pending"
                        },
                        new
                        {
                            StatusId = 2,
                            StatusName = "accepted"
                        },
                        new
                        {
                            StatusId = 3,
                            StatusName = "rejected"
                        },
                        new
                        {
                            StatusId = 4,
                            StatusName = "en_route"
                        },
                        new
                        {
                            StatusId = 5,
                            StatusName = "arrived"
                        },
                        new
                        {
                            StatusId = 6,
                            StatusName = "in_progress"
                        },
                        new
                        {
                            StatusId = 7,
                            StatusName = "completed"
                        },
                        new
                        {
                            StatusId = 8,
                            StatusName = "cancelled"
                        },
                        new
                        {
                            StatusId = 9,
                            StatusName = "emergency_pending"
                        },
                        new
                        {
                            StatusId = 10,
                            StatusName = "call_connecting"
                        },
                        new
                        {
                            StatusId = 11,
                            StatusName = "searching_responder"
                        },
                        new
                        {
                            StatusId = 12,
                            StatusName = "payment_pending"
                        },
                        new
                        {
                            StatusId = 13,
                            StatusName = "paid"
                        },
                        new
                        {
                            StatusId = 14,
                            StatusName = "call_connected"
                        });
                });

            modelBuilder.Entity("BikeMate.Core.Entities.RequestStatusHistory", b =>
                {
                    b.Property<int>("StatusHistoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("StatusHistoryId"));

                    b.Property<int?>("ChangedByUserId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("NewStatusId")
                        .HasColumnType("integer");

                    b.Property<string>("Notes")
                        .HasColumnType("text");

                    b.Property<int?>("OldStatusId")
                        .HasColumnType("integer");

                    b.Property<int>("RequestId")
                        .HasColumnType("integer");

                    b.HasKey("StatusHistoryId");

                    b.HasIndex("ChangedByUserId");

                    b.HasIndex("NewStatusId");

                    b.HasIndex("OldStatusId");

                    b.HasIndex("RequestId");

                    b.ToTable("request_status_history", (string)null);
                });

            modelBuilder.Entity("BikeMate.Core.Entities.Review", b =>
                {
                    b.Property<int>("ReviewId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ReviewId"));

                    b.Property<int>("ClientId")
                        .HasColumnType("integer");

                    b.Property<string>("Comment")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("MechanicId")
                        .HasColumnType("integer");

                    b.Property<int>("Rating")
                        .HasColumnType("integer");

                    b.Property<int>("RequestId")
                        .HasColumnType("integer");

                    b.HasKey("ReviewId");

                    b.HasIndex("ClientId");

                    b.HasIndex("MechanicId");

                    b.HasIndex("RequestId")
                        .IsUnique();

                    b.ToTable("reviews", (string)null);
                });

            modelBuilder.Entity("BikeMate.Core.Entities.Role", b =>
                {
                    b.Property<int>("RoleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("RoleId"));

                    b.Property<string>("RoleName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("RoleId");

                    b.HasIndex("RoleName")
                        .IsUnique();

                    b.ToTable("roles", (string)null);

                    b.HasData(
                        new
                        {
                            RoleId = 1,
                            RoleName = "Customer"
                        },
                        new
                        {
                            RoleId = 2,
                            RoleName = "Mechanic"
                        },
                        new
                        {
                            RoleId = 3,
                            RoleName = "ShopAdmin"
                        },
                        new
                        {
                            RoleId = 4,
                            RoleName = "SystemAdmin"
                        });
                });

            modelBuilder.Entity("BikeMate.Core.Entities.ServiceCategory", b =>
                {
                    b.Property<int>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("CategoryId"));

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("IconUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.HasKey("CategoryId");

                    b.HasIndex("CategoryName")
                        .IsUnique();

                    b.ToTable("service_categories", (string)null);

                    b.HasData(
                        new
                        {
                            CategoryId = 1,
                            CategoryName = "Engine Repair",
                            Description = "Engine troubleshooting, repair, and maintenance",
                            IsActive = true
                        },
                        new
                        {
                            CategoryId = 2,
                            CategoryName = "Tire Service",
                            Description = "Flat tire repair, tire replacement, and tire checking",
                            IsActive = true
                        },
                        new
                        {
                            CategoryId = 3,
                            CategoryName = "Battery Service",
                            Description = "Battery check, replacement, and charging assistance",
                            IsActive = true
                        },
                        new
                        {
                            CategoryId = 4,
                            CategoryName = "Oil Change",
                            Description = "Motorcycle oil change and fluid maintenance",
                            IsActive = true
                        },
                        new
                        {
                            CategoryId = 5,
                            CategoryName = "Brake Service",
                            Description = "Brake inspection, cleaning, repair, and replacement",
                            IsActive = true
                        },
                        new
                        {
                            CategoryId = 6,
                            CategoryName = "Emergency Roadside Assistance",
                            Description = "Urgent roadside motorcycle assistance",
                            IsActive = true
                        },
                        new
                        {
                            CategoryId = 7,
                            CategoryName = "Drivetrain & Gear Service",
                            Description = "Gear shifting, transmission, derailleur, and drivetrain diagnostics",
                            IsActive = true
                        },
                        new
                        {
                            CategoryId = 8,
                            CategoryName = "Chain & Sprocket Service",
                            Description = "Drive chain cleaning, tensioning, replacement, and sprocket inspection",
                            IsActive = true
                        },
                        new
                        {
                            CategoryId = 9,
                            CategoryName = "Accessories & Electrical Installation",
                            Description = "Safe installation of approved motorcycle accessories and electrical upgrades",
                            IsActive = true
                        },
                        new
                        {
                            CategoryId = 10,
                            CategoryName = "Preventive Maintenance & Tune-up",
                            Description = "Periodic inspection, adjustment, and complete motorcycle tune-up",
                            IsActive = true
                        });
                });

            modelBuilder.Entity("BikeMate.Core.Entities.ServiceImage", b =>
                {
                    b.Property<int>("ServiceImageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ServiceImageId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int>("ShopServiceId")
                        .HasColumnType("integer");

                    b.HasKey("ServiceImageId");

                    b.HasIndex("ShopServiceId");

                    b.ToTable("service_images", (string)null);
                });

            modelBuilder.Entity("BikeMate.Core.Entities.ServiceRequest", b =>
                {
                    b.Property<int>("RequestId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("RequestId"));

                    b.Property<DateTime?>("AcceptedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime?>("CancelledAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("ClientId")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("CurrentStatusId")
                        .HasColumnType("integer");

                    b.Property<decimal>("EstimatedTotal")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)");

                    b.Property<decimal>("FinalTotal")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)");

                    b.Property<string>("IssueDescription")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("MechanicId")
                        .HasColumnType("integer");

                    b.Property<int?>("MotorcycleId")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("ScheduledAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<decimal?>("ServiceLatitude")
                        .HasPrecision(10, 8)
                        .HasColumnType("numeric(10,8)");

                    b.Property<string>("ServiceLocationAddress")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<decimal?>("ServiceLongitude")
                        .HasPrecision(11, 8)
                        .HasColumnType("numeric(11,8)");

                    b.Property<int?>("ShopId")
                        .HasColumnType("integer");

                    b.Property<int?>("ShopServiceId")
                        .HasColumnType("integer");

                    b.HasKey("RequestId");

                    b.HasIndex("ClientId");

                    b.HasIndex("CurrentStatusId");

                    b.HasIndex("MechanicId");

                    b.HasIndex("MotorcycleId");

                    b.HasIndex("ShopId");

                    b.HasIndex("ShopServiceId");

                    b.ToTable("service_requests", (string)null);
                });

            modelBuilder.Entity("BikeMate.Core.Entities.ServiceRequestLineItem", b =>
                {
                    b.Property<int>("LineItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("LineItemId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("ItemName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("ItemType")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<decimal>("LineTotal")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)");

                    b.Property<int?>("ProductId")
                        .HasColumnType("integer");

                    b.Property<int>("Quantity")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1);

                    b.Property<int>("RequestId")
                        .HasColumnType("integer");

                    b.Property<int?>("ShopServiceId")
                        .HasColumnType("integer");

                    b.Property<decimal>("UnitPrice")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)");

                    b.HasKey("LineItemId");

                    b.HasIndex("ProductId");

                    b.HasIndex("RequestId");

                    b.HasIndex("ShopServiceId");

                    b.ToTable("service_request_line_items", (string)null);
                });

            modelBuilder.Entity("BikeMate.Core.Entities.Shop", b =>
                {
                    b.Property<int>("ShopId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ShopId"));

                    b.Property<string>("AddressLine")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<bool>("AllowsOnsiteRepair")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<bool>("AllowsPickup")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<bool>("AllowsReservations")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<string>("BusinessPermitUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("City")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("ContactNumber")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<decimal?>("Latitude")
                        .HasPrecision(10, 8)
                        .HasColumnType("numeric(10,8)");

                    b.Property<decimal?>("Longitude")
                        .HasPrecision(11, 8)
                        .HasColumnType("numeric(11,8)");

                    b.Property<string>("OwnerAddressLine")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("OwnerBarangay")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime?>("OwnerBirthdate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("OwnerCity")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("OwnerMiddleName")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("OwnerProvince")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("OwnerSex")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<int>("OwnerUserId")
                        .HasColumnType("integer");

                    b.Property<string>("OwnerValidIdUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("OwnerZipCode")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<string>("Province")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("ShopDescription")
                        .HasColumnType("text");

                    b.Property<string>("ShopImageUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("ShopLogoUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("ShopName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("ShopStatus")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasDefaultValue("pending");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("ShopId");

                    b.HasIndex("OwnerUserId");

                    b.ToTable("shops", (string)null);

                    b.HasData(
                        new
                        {
                            ShopId = 1,
                            AllowsOnsiteRepair = true,
                            AllowsPickup = true,
                            AllowsReservations = true,
                            City = "Manila",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            OwnerUserId = 4,
                            Province = "NCR",
                            ShopName = "Demo Bike Shop",
                            ShopStatus = "active"
                        });
                });

            modelBuilder.Entity("BikeMate.Core.Entities.ShopMechanic", b =>
                {
                    b.Property<int>("ShopId")
                        .HasColumnType("integer");

                    b.Property<int>("MechanicId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("AssignedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.HasKey("ShopId", "MechanicId");

                    b.HasIndex("MechanicId");

                    b.ToTable("shop_mechanics", (string)null);
                });

            modelBuilder.Entity("BikeMate.Core.Entities.ShopOperatingHour", b =>
                {
                    b.Property<int>("OperatingHourId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("OperatingHourId"));

                    b.Property<TimeSpan>("ClosingTime")
                        .HasColumnType("interval");

                    b.Property<int>("DayOfWeek")
                        .HasColumnType("integer");

                    b.Property<bool>("IsClosed")
                        .HasColumnType("boolean");

                    b.Property<TimeSpan>("OpeningTime")
                        .HasColumnType("interval");

                    b.Property<int>("ShopId")
                        .HasColumnType("integer");

                    b.HasKey("OperatingHourId");

                    b.HasIndex("ShopId");

                    b.ToTable("shop_operating_hours", (string)null);
                });

            modelBuilder.Entity("BikeMate.Core.Entities.ShopService", b =>
                {
                    b.Property<int>("ShopServiceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ShopServiceId"));

                    b.Property<decimal>("BasePrice")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)");

                    b.Property<int>("CategoryId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("EstimatedMinutes")
                        .HasColumnType("integer");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("ServiceDescription")
                        .HasColumnType("text");

                    b.Property<string>("ServiceName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<int>("ShopId")
                        .HasColumnType("integer");

                    b.HasKey("ShopServiceId");

                    b.HasIndex("CategoryId");

                    b.HasIndex("ShopId");

                    b.ToTable("shop_services", (string)null);
                });

            modelBuilder.Entity("BikeMate.Core.Entities.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("UserId"));

                    b.Property<string>("AccountStatus")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasDefaultValue("pending");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<bool>("EmailVerified")
                        .HasColumnType("boolean");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("PasswordHash")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<bool>("PhoneVerified")
                        .HasColumnType("boolean");

                    b.Property<string>("ProfileImageUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("UserId");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("users", (string)null);

                    b.HasData(
                        new
                        {
                            UserId = 1,
                            AccountStatus = "active",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "isaiahandreinoda@gmail.com",
                            EmailVerified = true,
                            FirstName = "Isaiah",
                            LastName = "Noda",
                            PasswordHash = "sha256:588c55f3ce2b8569b153c5abbf13f9f74308b88a20017cc699b835cc93195d16",
                            PhoneNumber = "+639170000001",
                            PhoneVerified = true
                        },
                        new
                        {
                            UserId = 2,
                            AccountStatus = "active",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "customer1@bikemate.test",
                            EmailVerified = true,
                            FirstName = "John",
                            LastName = "Doe",
                            PasswordHash = "sha256:588c55f3ce2b8569b153c5abbf13f9f74308b88a20017cc699b835cc93195d16",
                            PhoneNumber = "+639170000002",
                            PhoneVerified = true
                        },
                        new
                        {
                            UserId = 3,
                            AccountStatus = "active",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "mechanic1@bikemate.test",
                            EmailVerified = true,
                            FirstName = "Jane",
                            LastName = "Smith",
                            PasswordHash = "sha256:588c55f3ce2b8569b153c5abbf13f9f74308b88a20017cc699b835cc93195d16",
                            PhoneNumber = "+639170000003",
                            PhoneVerified = true
                        },
                        new
                        {
                            UserId = 4,
                            AccountStatus = "active",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "shop1@bikemate.test",
                            EmailVerified = true,
                            FirstName = "Bob",
                            LastName = "Williams",
                            PasswordHash = "sha256:588c55f3ce2b8569b153c5abbf13f9f74308b88a20017cc699b835cc93195d16",
                            PhoneNumber = "+639170000004",
                            PhoneVerified = true
                        });
                });

            modelBuilder.Entity("BikeMate.Core.Entities.UserAuthProvider", b =>
                {
                    b.Property<int>("AuthProviderId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("AuthProviderId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("ProviderEmail")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("ProviderName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("ProviderSubject")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("AuthProviderId");

                    b.HasIndex("UserId");

                    b.HasIndex("ProviderName", "ProviderSubject")
                        .IsUnique()
                        .HasFilter("\"ProviderSubject\" IS NOT NULL");

                    b.ToTable("user_auth_providers", (string)null);
                });

            modelBuilder.Entity("BikeMate.Core.Entities.UserDeviceToken", b =>
                {
                    b.Property<int>("DeviceTokenId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("DeviceTokenId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("DeviceToken")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Platform")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasDefaultValue("android");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("DeviceTokenId");

                    b.HasIndex("UserId");

                    b.ToTable("user_device_tokens", (string)null);
                });

            modelBuilder.Entity("BikeMate.Core.Entities.UserRole", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.Property<int>("RoleId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("AssignedAt")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("user_roles", (string)null);

                    b.HasData(
                        new
                        {
                            UserId = 1,
                            RoleId = 4,
                            AssignedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            UserId = 2,
                            RoleId = 1,
                            AssignedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            UserId = 3,
                            RoleId = 2,
                            AssignedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            UserId = 4,
                            RoleId = 3,
                            AssignedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("BikeMate.Core.Entities.AuditLog", b =>
                {
                    b.HasOne("BikeMate.Core.Entities.User", "ActorUser")
                        .WithMany()
                        .HasForeignKey("ActorUserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("ActorUser");
                });

            modelBuilder.Entity("BikeMate.Core.Entities.Client", b =>
                {
                    b.HasOne("BikeMate.Core.Entities.User", "User")
                        .WithOne("Client")
                        .HasForeignKey("BikeMate.Core.Entities.Client", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("BikeMate.Core.Entities.ClientAddress", b =>
                {
                    b.HasOne("BikeMate.Core.Entities.Client", "Client")
                        .WithMany("Addresses")
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Client");
                });

            modelBuilder.Entity("BikeMate.Core.Entities.Conversation", b =>
                {
                    b.HasOne("BikeMate.Core.Entities.ServiceRequest", "Request")
                        .WithMany()
                        .HasForeignKey("RequestId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Request");
                });

            modelBuilder.Entity("BikeMate.Core.Entities.ConversationParticipant", b =>
                {
                    b.HasOne("BikeMate.Core.Entities.Conversation", "Conversation")
                        .WithMany("Participants")
                        .HasForeignKey("ConversationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BikeMate.Core.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Conversation");

                    b.Navigation("User");
                });

            modelBuilder.Entity("BikeMate.Core.Entities.LiveLocation", b =>
                {
                    b.HasOne("BikeMate.Core.Entities.Mechanic", "Mechanic")
                        .WithMany("LiveLocations")
                        .HasForeignKey("MechanicId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("BikeMate.Core.Entities.ServiceRequest", "Request")
                        .WithMany("LiveLocations")
                        .HasForeignKey("RequestId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Mechanic");

                    b.Navigation("Request");
                });

            modelBuilder.Entity("BikeMate.Core.Entities.Mechanic", b =>
                {
                    b.HasOne("BikeMate.Core.Entities.User", "User")
                        .WithOne("Mechanic")
                        .HasForeignKey("BikeMate.Core.Entities.Mechanic", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("BikeMate.Core.Entities.MechanicAvailability", b =>
                {
                    b.HasOne("BikeMate.Core.Entities.Mechanic", "Mechanic")
                        .WithMany("Availability")
                        .HasForeignKey("MechanicId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Mechanic");
                });

            modelBuilder.Entity("BikeMate.Core.Entities.Message", b =>
                {
                    b.HasOne("BikeMate.Core.Entities.Conversation", "Conversation")
                        .WithMany("Messages")
                        .HasForeignKey("ConversationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BikeMate.Core.Entities.User", "Sender")
                        .WithMany()
                        .HasForeignKey("SenderUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Conversation");

                    b.Navigation("Sender");
                });

            modelBuilder.Entity("BikeMate.Core.Entities.Motorcycle", b =>
                {
                    b.HasOne("BikeMate.Core.Entities.Client", "Client")
                        .WithMany("Motorcycles")
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Client");
                });

            modelBuilder.Entity("BikeMate.Core.Entities.Notification", b =>
                {
                    b.HasOne("BikeMate.Core.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("BikeMate.Core.Entities.OtpVerification", b =>
                {
                    b.HasOne("BikeMate.Core.Entities.User", "User")
                        .WithMany("OtpVerifications")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("BikeMate.Core.Entities.PasswordResetToken", b =>
                {
                    b.HasOne("BikeMate.Core.Entities.User", "User")
                        .WithMany("PasswordResetTokens")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("BikeMate.Core.Entities.Payment", b =>
                {
                    b.HasOne("BikeMate.Core.Entities.Client", "Client")
                        .WithMany("Payments")
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BikeMate.Core.Entities.PaymentMethod", "PaymentMethod")
                        .WithMany("Payments")
                        .HasForeignKey("PaymentMethodId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("BikeMate.Core.Entities.PaymentStatus", "PaymentStatus")
                        .WithMany("Payments")
                        .HasForeignKey("PaymentStatusId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BikeMate.Core.Entities.ServiceRequest", "Request")
                        .WithMany("Payments")
                        .HasForeignKey("RequestId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Client");

                    b.Navigation("PaymentMethod");

                    b.Navigation("PaymentStatus");

                    b.Navigation("Request");
                });

            modelBuilder.Entity("BikeMate.Core.Entities.PaymentEvent", b =>
                {
                    b.HasOne("BikeMate.Core.Entities.Payment", "Payment")
                        .WithMany("Events")
                        .HasForeignKey("PaymentId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Payment");
                });

            modelBuilder.Entity("BikeMate.Core.Entities.Product", b =>
                {
                    b.HasOne("BikeMate.Core.Entities.Shop", "Shop")
                        .WithMany("Products")
                        .HasForeignKey("ShopId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Shop");
                });

            modelBuilder.Entity("BikeMate.Core.Entities.ProductImage", b =>
                {
                    b.HasOne("BikeMate.Core.Entities.Product", "Product")
                        .WithMany("Images")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("BikeMate.Core.Entities.RequestMedia", b =>
                {
                    b.HasOne("BikeMate.Core.Entities.ServiceRequest", "Request")
                        .WithMany("Media")
                        .HasForeignKey("RequestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Request");
                });

            modelBuilder.Entity("BikeMate.Core.Entities.RequestStatusHistory", b =>
                {
                    b.HasOne("BikeMate.Core.Entities.User", "ChangedByUser")
                        .WithMany()
                        .HasForeignKey("ChangedByUserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("BikeMate.Core.Entities.RequestStatus", "NewStatus")
                        .WithMany()
                        .HasForeignKey("NewStatusId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BikeMate.Core.Entities.RequestStatus", "OldStatus")
                        .WithMany()
                        .HasForeignKey("OldStatusId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("BikeMate.Core.Entities.ServiceRequest", "Request")
                        .WithMany("StatusHistory")
                        .HasForeignKey("RequestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ChangedByUser");

                    b.Navigation("NewStatus");

                    b.Navigation("OldStatus");

                    b.Navigation("Request");
                });

            modelBuilder.Entity("BikeMate.Core.Entities.Review", b =>
                {
                    b.HasOne("BikeMate.Core.Entities.Client", "Client")
                        .WithMany()
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BikeMate.Core.Entities.Mechanic", "Mechanic")
                        .WithMany("Reviews")
                        .HasForeignKey("MechanicId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BikeMate.Core.Entities.ServiceRequest", "Request")
                        .WithOne("Review")
                        .HasForeignKey("BikeMate.Core.Entities.Review", "RequestId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Client");

                    b.Navigation("Mechanic");

                    b.Navigation("Request");
                });

            modelBuilder.Entity("BikeMate.Core.Entities.ServiceImage", b =>
                {
                    b.HasOne("BikeMate.Core.Entities.ShopService", "ShopService")
                        .WithMany("Images")
                        .HasForeignKey("ShopServiceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ShopService");
                });

            modelBuilder.Entity("BikeMate.Core.Entities.ServiceRequest", b =>
                {
                    b.HasOne("BikeMate.Core.Entities.Client", "Client")
                        .WithMany("ServiceRequests")
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BikeMate.Core.Entities.RequestStatus", "CurrentStatus")
                        .WithMany("ServiceRequests")
                        .HasForeignKey("CurrentStatusId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BikeMate.Core.Entities.Mechanic", "Mechanic")
                        .WithMany("AssignedRequests")
                        .HasForeignKey("MechanicId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("BikeMate.Core.Entities.Motorcycle", "Motorcycle")
                        .WithMany()
                        .HasForeignKey("MotorcycleId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("BikeMate.Core.Entities.Shop", "Shop")
                        .WithMany("ServiceRequests")
                        .HasForeignKey("ShopId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("BikeMate.Core.Entities.ShopService", "ShopService")
                        .WithMany("ServiceRequests")
                        .HasForeignKey("ShopServiceId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Client");

                    b.Navigation("CurrentStatus");

                    b.Navigation("Mechanic");

                    b.Navigation("Motorcycle");

                    b.Navigation("Shop");

                    b.Navigation("ShopService");
                });

            modelBuilder.Entity("BikeMate.Core.Entities.ServiceRequestLineItem", b =>
                {
                    b.HasOne("BikeMate.Core.Entities.Product", "Product")
                        .WithMany("RequestLineItems")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("BikeMate.Core.Entities.ServiceRequest", "Request")
                        .WithMany("LineItems")
                        .HasForeignKey("RequestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BikeMate.Core.Entities.ShopService", "ShopService")
                        .WithMany()
                        .HasForeignKey("ShopServiceId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Product");

                    b.Navigation("Request");

                    b.Navigation("ShopService");
                });

            modelBuilder.Entity("BikeMate.Core.Entities.Shop", b =>
                {
                    b.HasOne("BikeMate.Core.Entities.User", "Owner")
                        .WithMany("OwnedShops")
                        .HasForeignKey("OwnerUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Owner");
                });

            modelBuilder.Entity("BikeMate.Core.Entities.ShopMechanic", b =>
                {
                    b.HasOne("BikeMate.Core.Entities.Mechanic", "Mechanic")
                        .WithMany("ShopMechanics")
                        .HasForeignKey("MechanicId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BikeMate.Core.Entities.Shop", "Shop")
                        .WithMany("ShopMechanics")
                        .HasForeignKey("ShopId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Mechanic");

                    b.Navigation("Shop");
                });

            modelBuilder.Entity("BikeMate.Core.Entities.ShopOperatingHour", b =>
                {
                    b.HasOne("BikeMate.Core.Entities.Shop", "Shop")
                        .WithMany("OperatingHours")
                        .HasForeignKey("ShopId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Shop");
                });

            modelBuilder.Entity("BikeMate.Core.Entities.ShopService", b =>
                {
                    b.HasOne("BikeMate.Core.Entities.ServiceCategory", "Category")
                        .WithMany("ShopServices")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BikeMate.Core.Entities.Shop", "Shop")
                        .WithMany("Services")
                        .HasForeignKey("ShopId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("Shop");
                });

            modelBuilder.Entity("BikeMate.Core.Entities.UserAuthProvider", b =>
                {
                    b.HasOne("BikeMate.Core.Entities.User", "User")
                        .WithMany("AuthProviders")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("BikeMate.Core.Entities.UserDeviceToken", b =>
                {
                    b.HasOne("BikeMate.Core.Entities.User", "User")
                        .WithMany("DeviceTokens")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("BikeMate.Core.Entities.UserRole", b =>
                {
                    b.HasOne("BikeMate.Core.Entities.Role", "Role")
                        .WithMany("UserRoles")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BikeMate.Core.Entities.User", "User")
                        .WithMany("UserRoles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");

                    b.Navigation("User");
                });

            modelBuilder.Entity("BikeMate.Core.Entities.Client", b =>
                {
                    b.Navigation("Addresses");

                    b.Navigation("Motorcycles");

                    b.Navigation("Payments");

                    b.Navigation("ServiceRequests");
                });

            modelBuilder.Entity("BikeMate.Core.Entities.Conversation", b =>
                {
                    b.Navigation("Messages");

                    b.Navigation("Participants");
                });

            modelBuilder.Entity("BikeMate.Core.Entities.Mechanic", b =>
                {
                    b.Navigation("AssignedRequests");

                    b.Navigation("Availability");

                    b.Navigation("LiveLocations");

                    b.Navigation("Reviews");

                    b.Navigation("ShopMechanics");
                });

            modelBuilder.Entity("BikeMate.Core.Entities.Payment", b =>
                {
                    b.Navigation("Events");
                });

            modelBuilder.Entity("BikeMate.Core.Entities.PaymentMethod", b =>
                {
                    b.Navigation("Payments");
                });

            modelBuilder.Entity("BikeMate.Core.Entities.PaymentStatus", b =>
                {
                    b.Navigation("Payments");
                });

            modelBuilder.Entity("BikeMate.Core.Entities.Product", b =>
                {
                    b.Navigation("Images");

                    b.Navigation("RequestLineItems");
                });

            modelBuilder.Entity("BikeMate.Core.Entities.RequestStatus", b =>
                {
                    b.Navigation("ServiceRequests");
                });

            modelBuilder.Entity("BikeMate.Core.Entities.Role", b =>
                {
                    b.Navigation("UserRoles");
                });

            modelBuilder.Entity("BikeMate.Core.Entities.ServiceCategory", b =>
                {
                    b.Navigation("ShopServices");
                });

            modelBuilder.Entity("BikeMate.Core.Entities.ServiceRequest", b =>
                {
                    b.Navigation("LineItems");

                    b.Navigation("LiveLocations");

                    b.Navigation("Media");

                    b.Navigation("Payments");

                    b.Navigation("Review");

                    b.Navigation("StatusHistory");
                });

            modelBuilder.Entity("BikeMate.Core.Entities.Shop", b =>
                {
                    b.Navigation("OperatingHours");

                    b.Navigation("Products");

                    b.Navigation("ServiceRequests");

                    b.Navigation("Services");

                    b.Navigation("ShopMechanics");
                });

            modelBuilder.Entity("BikeMate.Core.Entities.ShopService", b =>
                {
                    b.Navigation("Images");

                    b.Navigation("ServiceRequests");
                });

            modelBuilder.Entity("BikeMate.Core.Entities.User", b =>
                {
                    b.Navigation("AuthProviders");

                    b.Navigation("Client");

                    b.Navigation("DeviceTokens");

                    b.Navigation("Mechanic");

                    b.Navigation("OtpVerifications");

                    b.Navigation("OwnedShops");

                    b.Navigation("PasswordResetTokens");

                    b.Navigation("UserRoles");
                });
#pragma warning restore 612, 618
        }
    }
}
