FROM mcr.microsoft.com/dotnet/sdk:10.0 AS build
WORKDIR /src

COPY BikeMate.Core/BikeMate.Core.csproj BikeMate.Core/
COPY BikeMate.Infrastructure/BikeMate.Infrastructure.csproj BikeMate.Infrastructure/
COPY "BikeMate.WebAdmin/BikeMate.WebAdmin/BikeMate.WebAdmin.csproj" "BikeMate.WebAdmin/BikeMate.WebAdmin/"
RUN dotnet restore "BikeMate.WebAdmin/BikeMate.WebAdmin/BikeMate.WebAdmin.csproj"

COPY . .
RUN dotnet publish "BikeMate.WebAdmin/BikeMate.WebAdmin/BikeMate.WebAdmin.csproj" -c Release -o /app --no-restore

FROM mcr.microsoft.com/dotnet/aspnet:10.0 AS runtime
WORKDIR /app
COPY --from=build /app .
EXPOSE 8080
ENV ASPNETCORE_URLS=http://+:8080
ENTRYPOINT ["dotnet", "BikeMate.WebAdmin.dll"]
