// <auto-generated />
using System;
using BikeMate.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BikeMate.Infrastructure.Migrations
{
    [DbContext(typeof(BikeMateDbContext))]
    [Migration("20260624144659_AddCustomerAccountDetails")]
    partial class AddCustomerAccountDetails
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("dbo")
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BikeMate.Core.Entities.AuditLog", b =>
                {
                    b.Property<int>("AuditId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AuditId"));

                    b.Property<string>("ActionName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("ActorUserId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<string>("EntityId")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("EntityName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("NewValuesJson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OldValuesJson")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("AuditId");

                    b.HasIndex("ActorUserId");

                    b.ToTable("audit_logs", "dbo");
                });

            modelBuilder.Entity("BikeMate.Core.Entities.Client", b =>
                {
                    b.Property<int>("ClientId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ClientId"));

                    b.Property<DateTime?>("Birthdate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<string>("MiddleName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Sex")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<string>("ValidIdImageUrl")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("ClientId");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("clients", "dbo");

                    b.HasData(
                        new
                        {
                            ClientId = 1,
                            CreatedAt = new DateTime(2026, 6, 8, 0, 0, 0, 0, DateTimeKind.Utc),
                            UserId = 1
                        });
                });

            modelBuilder.Entity("BikeMate.Core.Entities.ClientAddress", b =>
                {
                    b.Property<int>("AddressId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AddressId"));

                    b.Property<string>("AddressLine")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Barangay")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("City")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("ClientId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<bool>("IsDefault")
                        .HasColumnType("bit");

                    b.Property<string>("Label")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal?>("Latitude")
                        .HasPrecision(10, 8)
                        .HasColumnType("decimal(10,8)");

                    b.Property<decimal?>("Longitude")
                        .HasPrecision(11, 8)
                        .HasColumnType("decimal(11,8)");

                    b.Property<string>("PostalCode")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Province")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("AddressId");

                    b.HasIndex("ClientId");

                    b.ToTable("client_addresses", "dbo");

                    b.HasData(
                        new
                        {
                            AddressId = 1,
                            AddressLine = "Sample customer address, Manila",
                            City = "Manila",
                            ClientId = 1,
                            CreatedAt = new DateTime(2026, 6, 8, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsDefault = true,
                            Label = "Home",
                            Latitude = 14.599512m,
                            Longitude = 120.984222m,
                            PostalCode = "1000",
                            Province = "Metro Manila"
                        });
                });

            modelBuilder.Entity("BikeMate.Core.Entities.Conversation", b =>
                {
                    b.Property<int>("ConversationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ConversationId"));

                    b.Property<string>("ConversationType")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasDefaultValue("service_request");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<DateTime?>("LastMessageAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("RequestId")
                        .HasColumnType("int");

                    b.HasKey("ConversationId");

                    b.HasIndex("RequestId");

                    b.ToTable("conversations", "dbo");

                    b.HasData(
                        new
                        {
                            ConversationId = 1,
                            ConversationType = "service_request",
                            CreatedAt = new DateTime(2026, 6, 8, 0, 0, 0, 0, DateTimeKind.Utc),
                            LastMessageAt = new DateTime(2026, 6, 8, 0, 20, 0, 0, DateTimeKind.Utc),
                            RequestId = 1
                        });
                });

            modelBuilder.Entity("BikeMate.Core.Entities.ConversationParticipant", b =>
                {
                    b.Property<int>("ConversationId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<DateTime>("JoinedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<DateTime?>("LastReadAt")
                        .HasColumnType("datetime2");

                    b.HasKey("ConversationId", "UserId");

                    b.HasIndex("UserId");

                    b.ToTable("conversation_participants", "dbo");

                    b.HasData(
                        new
                        {
                            ConversationId = 1,
                            UserId = 1,
                            JoinedAt = new DateTime(2026, 6, 8, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            ConversationId = 1,
                            UserId = 2,
                            JoinedAt = new DateTime(2026, 6, 8, 0, 0, 0, 0, DateTimeKind.Utc)
                        });
                });

            modelBuilder.Entity("BikeMate.Core.Entities.LiveLocation", b =>
                {
                    b.Property<int>("LiveLocationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LiveLocationId"));

                    b.Property<decimal?>("AccuracyMeters")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<decimal>("Latitude")
                        .HasPrecision(10, 8)
                        .HasColumnType("decimal(10,8)");

                    b.Property<decimal>("Longitude")
                        .HasPrecision(11, 8)
                        .HasColumnType("decimal(11,8)");

                    b.Property<int?>("MechanicId")
                        .HasColumnType("int");

                    b.Property<int?>("RequestId")
                        .HasColumnType("int");

                    b.HasKey("LiveLocationId");

                    b.HasIndex("MechanicId");

                    b.HasIndex("RequestId");

                    b.ToTable("live_locations", "dbo");

                    b.HasData(
                        new
                        {
                            LiveLocationId = 1,
                            AccuracyMeters = 8m,
                            CreatedAt = new DateTime(2026, 6, 8, 0, 25, 0, 0, DateTimeKind.Utc),
                            Latitude = 14.6010m,
                            Longitude = 120.9830m,
                            MechanicId = 1,
                            RequestId = 1
                        });
                });

            modelBuilder.Entity("BikeMate.Core.Entities.Mechanic", b =>
                {
                    b.Property<int>("MechanicId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MechanicId"));

                    b.Property<string>("AvailabilityStatus")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasDefaultValue("offline");

                    b.Property<decimal>("AverageRating")
                        .HasPrecision(3, 2)
                        .HasColumnType("decimal(3,2)");

                    b.Property<string>("Bio")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CertificationImageUrl")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<decimal?>("CurrentLatitude")
                        .HasPrecision(10, 8)
                        .HasColumnType("decimal(10,8)");

                    b.Property<decimal?>("CurrentLongitude")
                        .HasPrecision(11, 8)
                        .HasColumnType("decimal(11,8)");

                    b.Property<bool>("IsVerified")
                        .HasColumnType("bit");

                    b.Property<int>("TotalCompletedJobs")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int?>("YearsExperience")
                        .HasColumnType("int");

                    b.HasKey("MechanicId");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("mechanics", "dbo");

                    b.HasData(
                        new
                        {
                            MechanicId = 1,
                            AvailabilityStatus = "online",
                            AverageRating = 4.80m,
                            Bio = "Certified roadside motorcycle technician.",
                            CreatedAt = new DateTime(2026, 6, 8, 0, 0, 0, 0, DateTimeKind.Utc),
                            CurrentLatitude = 14.599512m,
                            CurrentLongitude = 120.984222m,
                            IsVerified = true,
                            TotalCompletedJobs = 12,
                            UserId = 2,
                            YearsExperience = 5
                        });
                });

            modelBuilder.Entity("BikeMate.Core.Entities.MechanicAvailability", b =>
                {
                    b.Property<int>("AvailabilityId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AvailabilityId"));

                    b.Property<int>("DayOfWeek")
                        .HasColumnType("int");

                    b.Property<TimeSpan>("EndTime")
                        .HasColumnType("time");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<int>("MechanicId")
                        .HasColumnType("int");

                    b.Property<TimeSpan>("StartTime")
                        .HasColumnType("time");

                    b.HasKey("AvailabilityId");

                    b.HasIndex("MechanicId");

                    b.ToTable("mechanic_availability", "dbo");
                });

            modelBuilder.Entity("BikeMate.Core.Entities.Message", b =>
                {
                    b.Property<int>("MessageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MessageId"));

                    b.Property<string>("AttachmentUrl")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("ConversationId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<string>("MessageText")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ReadAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("SenderUserId")
                        .HasColumnType("int");

                    b.HasKey("MessageId");

                    b.HasIndex("ConversationId");

                    b.HasIndex("SenderUserId");

                    b.ToTable("messages", "dbo");

                    b.HasData(
                        new
                        {
                            MessageId = 1,
                            ConversationId = 1,
                            CreatedAt = new DateTime(2026, 6, 8, 0, 20, 0, 0, DateTimeKind.Utc),
                            MessageText = "I am on the way to your location.",
                            SenderUserId = 2
                        });
                });

            modelBuilder.Entity("BikeMate.Core.Entities.Motorcycle", b =>
                {
                    b.Property<int>("MotorcycleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MotorcycleId"));

                    b.Property<string>("Brand")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("ClientId")
                        .HasColumnType("int");

                    b.Property<string>("Color")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<string>("EngineType")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("MotorcycleImageUrl")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("PlateNumber")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("YearModel")
                        .HasColumnType("int");

                    b.HasKey("MotorcycleId");

                    b.HasIndex("ClientId");

                    b.ToTable("motorcycles", "dbo");

                    b.HasData(
                        new
                        {
                            MotorcycleId = 1,
                            Brand = "Honda",
                            ClientId = 1,
                            Color = "Black",
                            CreatedAt = new DateTime(2026, 6, 8, 0, 0, 0, 0, DateTimeKind.Utc),
                            EngineType = "125cc",
                            Model = "Click 125i",
                            PlateNumber = "BM-1234",
                            YearModel = 2022
                        });
                });

            modelBuilder.Entity("BikeMate.Core.Entities.Notification", b =>
                {
                    b.Property<int>("NotificationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("NotificationId"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<string>("DataJson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsRead")
                        .HasColumnType("bit");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NotificationType")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("NotificationId");

                    b.HasIndex("UserId");

                    b.ToTable("notifications", "dbo");

                    b.HasData(
                        new
                        {
                            NotificationId = 1,
                            CreatedAt = new DateTime(2026, 6, 8, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsRead = false,
                            Message = "Rico Mechanic accepted your tire service request.",
                            NotificationType = "booking",
                            Title = "Mechanic assigned",
                            UserId = 1
                        });
                });

            modelBuilder.Entity("BikeMate.Core.Entities.OtpVerification", b =>
                {
                    b.Property<int>("OtpId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("OtpId"));

                    b.Property<int>("Attempts")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ConsumedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("OtpHash")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Purpose")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasDefaultValue("email_verification");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("OtpId");

                    b.HasIndex("UserId");

                    b.ToTable("otp_verifications", "dbo");
                });

            modelBuilder.Entity("BikeMate.Core.Entities.PasswordResetToken", b =>
                {
                    b.Property<int>("TokenId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TokenId"));

                    b.Property<DateTime?>("ConsumedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("TokenId");

                    b.HasIndex("UserId");

                    b.ToTable("password_reset_tokens", "dbo");
                });

            modelBuilder.Entity("BikeMate.Core.Entities.Payment", b =>
                {
                    b.Property<int>("PaymentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PaymentId"));

                    b.Property<decimal>("Amount")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<string>("CheckoutUrl")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int>("ClientId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasDefaultValue("PHP");

                    b.Property<DateTime?>("PaidAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("PaymentMethodId")
                        .HasColumnType("int");

                    b.Property<int>("PaymentStatusId")
                        .HasColumnType("int");

                    b.Property<string>("ProviderCheckoutSessionId")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("ProviderName")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasDefaultValue("paymongo");

                    b.Property<string>("ProviderPaymentId")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("ProviderReferenceNumber")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("RequestId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("PaymentId");

                    b.HasIndex("ClientId");

                    b.HasIndex("PaymentMethodId");

                    b.HasIndex("PaymentStatusId");

                    b.HasIndex("RequestId");

                    b.ToTable("payments", "dbo");

                    b.HasData(
                        new
                        {
                            PaymentId = 1,
                            Amount = 350m,
                            CheckoutUrl = "https://checkout.paymongo.com/test/bikemate-sample",
                            ClientId = 1,
                            CreatedAt = new DateTime(2026, 6, 8, 0, 0, 0, 0, DateTimeKind.Utc),
                            Currency = "PHP",
                            PaidAt = new DateTime(2026, 6, 8, 0, 30, 0, 0, DateTimeKind.Utc),
                            PaymentMethodId = 1,
                            PaymentStatusId = 3,
                            ProviderName = "paymongo",
                            ProviderReferenceNumber = "BM-PAID-0001",
                            RequestId = 1,
                            UpdatedAt = new DateTime(2026, 6, 8, 0, 30, 0, 0, DateTimeKind.Utc)
                        });
                });

            modelBuilder.Entity("BikeMate.Core.Entities.PaymentEvent", b =>
                {
                    b.Property<int>("PaymentEventId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PaymentEventId"));

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("PayloadJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("PaymentId")
                        .HasColumnType("int");

                    b.Property<string>("ProviderEventId")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime>("ReceivedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.HasKey("PaymentEventId");

                    b.HasIndex("PaymentId");

                    b.ToTable("payment_events", "dbo");
                });

            modelBuilder.Entity("BikeMate.Core.Entities.PaymentMethod", b =>
                {
                    b.Property<int>("PaymentMethodId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PaymentMethodId"));

                    b.Property<string>("MethodName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("PaymentMethodId");

                    b.HasIndex("MethodName")
                        .IsUnique();

                    b.ToTable("payment_methods", "dbo");

                    b.HasData(
                        new
                        {
                            PaymentMethodId = 1,
                            MethodName = "gcash"
                        },
                        new
                        {
                            PaymentMethodId = 2,
                            MethodName = "maya"
                        },
                        new
                        {
                            PaymentMethodId = 3,
                            MethodName = "card"
                        },
                        new
                        {
                            PaymentMethodId = 4,
                            MethodName = "grab_pay"
                        },
                        new
                        {
                            PaymentMethodId = 5,
                            MethodName = "cash"
                        },
                        new
                        {
                            PaymentMethodId = 6,
                            MethodName = "bank_transfer"
                        });
                });

            modelBuilder.Entity("BikeMate.Core.Entities.PaymentStatus", b =>
                {
                    b.Property<int>("PaymentStatusId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PaymentStatusId"));

                    b.Property<string>("StatusName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("PaymentStatusId");

                    b.HasIndex("StatusName")
                        .IsUnique();

                    b.ToTable("payment_statuses", "dbo");

                    b.HasData(
                        new
                        {
                            PaymentStatusId = 1,
                            StatusName = "unpaid"
                        },
                        new
                        {
                            PaymentStatusId = 2,
                            StatusName = "pending"
                        },
                        new
                        {
                            PaymentStatusId = 3,
                            StatusName = "paid"
                        },
                        new
                        {
                            PaymentStatusId = 4,
                            StatusName = "failed"
                        },
                        new
                        {
                            PaymentStatusId = 5,
                            StatusName = "cancelled"
                        },
                        new
                        {
                            PaymentStatusId = 6,
                            StatusName = "refunded"
                        });
                });

            modelBuilder.Entity("BikeMate.Core.Entities.Product", b =>
                {
                    b.Property<int>("ProductId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProductId"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<decimal>("Price")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<string>("ProductDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("ShopId")
                        .HasColumnType("int");

                    b.Property<int>("StockQuantity")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("ProductId");

                    b.HasIndex("ShopId");

                    b.ToTable("products", "dbo");

                    b.HasData(
                        new
                        {
                            ProductId = 1,
                            CreatedAt = new DateTime(2026, 6, 8, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Price = 280m,
                            ProductDescription = "Sample 10W-40 motorcycle oil.",
                            ProductName = "Engine Oil 1L",
                            ShopId = 1,
                            StockQuantity = 20
                        },
                        new
                        {
                            ProductId = 2,
                            CreatedAt = new DateTime(2026, 6, 8, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Price = 120m,
                            ProductDescription = "Patch kit for tubeless motorcycle tires.",
                            ProductName = "Tubeless Tire Patch",
                            ShopId = 1,
                            StockQuantity = 50
                        });
                });

            modelBuilder.Entity("BikeMate.Core.Entities.ProductImage", b =>
                {
                    b.Property<int>("ProductImageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProductImageId"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.HasKey("ProductImageId");

                    b.HasIndex("ProductId");

                    b.ToTable("product_images", "dbo");
                });

            modelBuilder.Entity("BikeMate.Core.Entities.RequestMedia", b =>
                {
                    b.Property<int>("RequestMediaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RequestMediaId"));

                    b.Property<string>("Caption")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<string>("MediaType")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasDefaultValue("image");

                    b.Property<string>("MediaUrl")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("RequestId")
                        .HasColumnType("int");

                    b.HasKey("RequestMediaId");

                    b.HasIndex("RequestId");

                    b.ToTable("request_media", "dbo");
                });

            modelBuilder.Entity("BikeMate.Core.Entities.RequestStatus", b =>
                {
                    b.Property<int>("StatusId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("StatusId"));

                    b.Property<string>("StatusName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("StatusId");

                    b.HasIndex("StatusName")
                        .IsUnique();

                    b.ToTable("request_statuses", "dbo");

                    b.HasData(
                        new
                        {
                            StatusId = 1,
                            StatusName = "pending"
                        },
                        new
                        {
                            StatusId = 2,
                            StatusName = "accepted"
                        },
                        new
                        {
                            StatusId = 3,
                            StatusName = "rejected"
                        },
                        new
                        {
                            StatusId = 4,
                            StatusName = "en_route"
                        },
                        new
                        {
                            StatusId = 5,
                            StatusName = "arrived"
                        },
                        new
                        {
                            StatusId = 6,
                            StatusName = "in_progress"
                        },
                        new
                        {
                            StatusId = 7,
                            StatusName = "completed"
                        },
                        new
                        {
                            StatusId = 8,
                            StatusName = "cancelled"
                        });
                });

            modelBuilder.Entity("BikeMate.Core.Entities.RequestStatusHistory", b =>
                {
                    b.Property<int>("StatusHistoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("StatusHistoryId"));

                    b.Property<int?>("ChangedByUserId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<int>("NewStatusId")
                        .HasColumnType("int");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("OldStatusId")
                        .HasColumnType("int");

                    b.Property<int>("RequestId")
                        .HasColumnType("int");

                    b.HasKey("StatusHistoryId");

                    b.HasIndex("ChangedByUserId");

                    b.HasIndex("NewStatusId");

                    b.HasIndex("OldStatusId");

                    b.HasIndex("RequestId");

                    b.ToTable("request_status_history", "dbo");
                });

            modelBuilder.Entity("BikeMate.Core.Entities.Review", b =>
                {
                    b.Property<int>("ReviewId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ReviewId"));

                    b.Property<int>("ClientId")
                        .HasColumnType("int");

                    b.Property<string>("Comment")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<int>("MechanicId")
                        .HasColumnType("int");

                    b.Property<int>("Rating")
                        .HasColumnType("int");

                    b.Property<int>("RequestId")
                        .HasColumnType("int");

                    b.HasKey("ReviewId");

                    b.HasIndex("ClientId");

                    b.HasIndex("MechanicId");

                    b.HasIndex("RequestId")
                        .IsUnique();

                    b.ToTable("reviews", "dbo", t =>
                        {
                            t.HasTrigger("trg_reviews_update_mechanic_rating");
                        });

                    b.HasAnnotation("SqlServer:UseSqlOutputClause", false);
                });

            modelBuilder.Entity("BikeMate.Core.Entities.Role", b =>
                {
                    b.Property<int>("RoleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RoleId"));

                    b.Property<string>("RoleName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("RoleId");

                    b.HasIndex("RoleName")
                        .IsUnique();

                    b.ToTable("roles", "dbo");

                    b.HasData(
                        new
                        {
                            RoleId = 1,
                            RoleName = "Customer"
                        },
                        new
                        {
                            RoleId = 2,
                            RoleName = "Mechanic"
                        },
                        new
                        {
                            RoleId = 3,
                            RoleName = "ShopAdmin"
                        },
                        new
                        {
                            RoleId = 4,
                            RoleName = "SystemAdmin"
                        });
                });

            modelBuilder.Entity("BikeMate.Core.Entities.ServiceCategory", b =>
                {
                    b.Property<int>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CategoryId"));

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IconUrl")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.HasKey("CategoryId");

                    b.HasIndex("CategoryName")
                        .IsUnique();

                    b.ToTable("service_categories", "dbo");

                    b.HasData(
                        new
                        {
                            CategoryId = 1,
                            CategoryName = "Engine Repair",
                            Description = "Engine troubleshooting, repair, and maintenance",
                            IsActive = true
                        },
                        new
                        {
                            CategoryId = 2,
                            CategoryName = "Tire Service",
                            Description = "Flat tire repair, tire replacement, and tire checking",
                            IsActive = true
                        },
                        new
                        {
                            CategoryId = 3,
                            CategoryName = "Battery Service",
                            Description = "Battery check, replacement, and charging assistance",
                            IsActive = true
                        },
                        new
                        {
                            CategoryId = 4,
                            CategoryName = "Oil Change",
                            Description = "Motorcycle oil change and fluid maintenance",
                            IsActive = true
                        },
                        new
                        {
                            CategoryId = 5,
                            CategoryName = "Brake Service",
                            Description = "Brake inspection, cleaning, repair, and replacement",
                            IsActive = true
                        },
                        new
                        {
                            CategoryId = 6,
                            CategoryName = "Emergency Roadside Assistance",
                            Description = "Urgent roadside motorcycle assistance",
                            IsActive = true
                        });
                });

            modelBuilder.Entity("BikeMate.Core.Entities.ServiceImage", b =>
                {
                    b.Property<int>("ServiceImageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ServiceImageId"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("ShopServiceId")
                        .HasColumnType("int");

                    b.HasKey("ServiceImageId");

                    b.HasIndex("ShopServiceId");

                    b.ToTable("service_images", "dbo");
                });

            modelBuilder.Entity("BikeMate.Core.Entities.ServiceRequest", b =>
                {
                    b.Property<int>("RequestId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RequestId"));

                    b.Property<DateTime?>("AcceptedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("CancelledAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("ClientId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<int>("CurrentStatusId")
                        .HasColumnType("int");

                    b.Property<decimal>("EstimatedTotal")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<decimal>("FinalTotal")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<string>("IssueDescription")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("MechanicId")
                        .HasColumnType("int");

                    b.Property<int?>("MotorcycleId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ScheduledAt")
                        .HasColumnType("datetime2");

                    b.Property<decimal?>("ServiceLatitude")
                        .HasPrecision(10, 8)
                        .HasColumnType("decimal(10,8)");

                    b.Property<string>("ServiceLocationAddress")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<decimal?>("ServiceLongitude")
                        .HasPrecision(11, 8)
                        .HasColumnType("decimal(11,8)");

                    b.Property<int?>("ShopId")
                        .HasColumnType("int");

                    b.Property<int?>("ShopServiceId")
                        .HasColumnType("int");

                    b.HasKey("RequestId");

                    b.HasIndex("ClientId");

                    b.HasIndex("CurrentStatusId");

                    b.HasIndex("MechanicId");

                    b.HasIndex("MotorcycleId");

                    b.HasIndex("ShopId");

                    b.HasIndex("ShopServiceId");

                    b.ToTable("service_requests", "dbo", t =>
                        {
                            t.HasTrigger("trg_requests_update_completed_jobs");

                            t.HasTrigger("trg_service_request_status_history");
                        });

                    b.HasAnnotation("SqlServer:UseSqlOutputClause", false);

                    b.HasData(
                        new
                        {
                            RequestId = 1,
                            AcceptedAt = new DateTime(2026, 6, 8, 0, 10, 0, 0, DateTimeKind.Utc),
                            ClientId = 1,
                            CreatedAt = new DateTime(2026, 6, 8, 0, 0, 0, 0, DateTimeKind.Utc),
                            CurrentStatusId = 6,
                            EstimatedTotal = 350m,
                            FinalTotal = 350m,
                            IssueDescription = "Rear tire is flat near home.",
                            MechanicId = 1,
                            MotorcycleId = 1,
                            ScheduledAt = new DateTime(2026, 6, 8, 10, 0, 0, 0, DateTimeKind.Utc),
                            ServiceLatitude = 14.599512m,
                            ServiceLocationAddress = "Sample customer address, Manila",
                            ServiceLongitude = 120.984222m,
                            ShopId = 1,
                            ShopServiceId = 1
                        },
                        new
                        {
                            RequestId = 2,
                            ClientId = 1,
                            CreatedAt = new DateTime(2026, 6, 8, 0, 0, 0, 0, DateTimeKind.Utc),
                            CurrentStatusId = 1,
                            EstimatedTotal = 500m,
                            FinalTotal = 0m,
                            IssueDescription = "Schedule oil change for next week.",
                            MotorcycleId = 1,
                            ScheduledAt = new DateTime(2026, 6, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            ServiceLatitude = 14.599512m,
                            ServiceLocationAddress = "Sample customer address, Manila",
                            ServiceLongitude = 120.984222m,
                            ShopId = 1,
                            ShopServiceId = 2
                        });
                });

            modelBuilder.Entity("BikeMate.Core.Entities.Shop", b =>
                {
                    b.Property<int>("ShopId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ShopId"));

                    b.Property<string>("AddressLine")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("BusinessPermitUrl")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("City")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ContactNumber")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<decimal?>("Latitude")
                        .HasPrecision(10, 8)
                        .HasColumnType("decimal(10,8)");

                    b.Property<decimal?>("Longitude")
                        .HasPrecision(11, 8)
                        .HasColumnType("decimal(11,8)");

                    b.Property<int>("OwnerUserId")
                        .HasColumnType("int");

                    b.Property<string>("Province")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ShopDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ShopImageUrl")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("ShopName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("ShopStatus")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasDefaultValue("pending");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("ShopId");

                    b.HasIndex("OwnerUserId");

                    b.ToTable("shops", "dbo");

                    b.HasData(
                        new
                        {
                            ShopId = 1,
                            AddressLine = "Sample shop address, Manila",
                            City = "Manila",
                            ContactNumber = "+639171234567",
                            CreatedAt = new DateTime(2026, 6, 8, 0, 0, 0, 0, DateTimeKind.Utc),
                            Latitude = 14.6042m,
                            Longitude = 120.9822m,
                            OwnerUserId = 3,
                            Province = "Metro Manila",
                            ShopDescription = "Sample verified repair shop for local testing.",
                            ShopName = "BikeMate Partner Shop",
                            ShopStatus = "verified"
                        });
                });

            modelBuilder.Entity("BikeMate.Core.Entities.ShopMechanic", b =>
                {
                    b.Property<int>("ShopId")
                        .HasColumnType("int");

                    b.Property<int>("MechanicId")
                        .HasColumnType("int");

                    b.Property<DateTime>("AssignedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.HasKey("ShopId", "MechanicId");

                    b.HasIndex("MechanicId");

                    b.ToTable("shop_mechanics", "dbo");

                    b.HasData(
                        new
                        {
                            ShopId = 1,
                            MechanicId = 1,
                            AssignedAt = new DateTime(2026, 6, 8, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true
                        });
                });

            modelBuilder.Entity("BikeMate.Core.Entities.ShopOperatingHour", b =>
                {
                    b.Property<int>("OperatingHourId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("OperatingHourId"));

                    b.Property<TimeSpan>("ClosingTime")
                        .HasColumnType("time");

                    b.Property<int>("DayOfWeek")
                        .HasColumnType("int");

                    b.Property<bool>("IsClosed")
                        .HasColumnType("bit");

                    b.Property<TimeSpan>("OpeningTime")
                        .HasColumnType("time");

                    b.Property<int>("ShopId")
                        .HasColumnType("int");

                    b.HasKey("OperatingHourId");

                    b.HasIndex("ShopId");

                    b.ToTable("shop_operating_hours", "dbo");
                });

            modelBuilder.Entity("BikeMate.Core.Entities.ShopService", b =>
                {
                    b.Property<int>("ShopServiceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ShopServiceId"));

                    b.Property<decimal>("BasePrice")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<int>("EstimatedMinutes")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("ServiceDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ServiceName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("ShopId")
                        .HasColumnType("int");

                    b.HasKey("ShopServiceId");

                    b.HasIndex("CategoryId");

                    b.HasIndex("ShopId");

                    b.ToTable("shop_services", "dbo");

                    b.HasData(
                        new
                        {
                            ShopServiceId = 1,
                            BasePrice = 350m,
                            CategoryId = 2,
                            CreatedAt = new DateTime(2026, 6, 8, 0, 0, 0, 0, DateTimeKind.Utc),
                            EstimatedMinutes = 45,
                            IsActive = true,
                            ServiceDescription = "On-site tire patching and tire check.",
                            ServiceName = "Flat Tire Rescue",
                            ShopId = 1
                        },
                        new
                        {
                            ShopServiceId = 2,
                            BasePrice = 500m,
                            CategoryId = 4,
                            CreatedAt = new DateTime(2026, 6, 8, 0, 0, 0, 0, DateTimeKind.Utc),
                            EstimatedMinutes = 60,
                            IsActive = true,
                            ServiceDescription = "Oil replacement and quick fluid inspection.",
                            ServiceName = "Basic Oil Change",
                            ShopId = 1
                        },
                        new
                        {
                            ShopServiceId = 3,
                            BasePrice = 700m,
                            CategoryId = 6,
                            CreatedAt = new DateTime(2026, 6, 8, 0, 0, 0, 0, DateTimeKind.Utc),
                            EstimatedMinutes = 40,
                            IsActive = true,
                            ServiceDescription = "Urgent assistance for breakdowns.",
                            ServiceName = "Emergency Roadside Help",
                            ShopId = 1
                        });
                });

            modelBuilder.Entity("BikeMate.Core.Entities.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserId"));

                    b.Property<string>("AccountStatus")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasDefaultValue("pending");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<bool>("EmailVerified")
                        .HasColumnType("bit");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PasswordHash")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("PhoneVerified")
                        .HasColumnType("bit");

                    b.Property<string>("ProfileImageUrl")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("UserId");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("users", "dbo");

                    b.HasData(
                        new
                        {
                            UserId = 1,
                            AccountStatus = "active",
                            CreatedAt = new DateTime(2026, 6, 8, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "customer@bikemate.test",
                            EmailVerified = true,
                            FirstName = "Juan",
                            LastName = "Customer",
                            PasswordHash = "sha256:a109e36947ad56de1dca1cc49f0ef8ac9ad9a7b1aa0df41fb3c4cb73c1ff01ea",
                            PhoneNumber = "+639171234567",
                            PhoneVerified = true
                        },
                        new
                        {
                            UserId = 2,
                            AccountStatus = "active",
                            CreatedAt = new DateTime(2026, 6, 8, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "mechanic@bikemate.test",
                            EmailVerified = true,
                            FirstName = "Rico",
                            LastName = "Mechanic",
                            PasswordHash = "sha256:a109e36947ad56de1dca1cc49f0ef8ac9ad9a7b1aa0df41fb3c4cb73c1ff01ea",
                            PhoneNumber = "+639171234567",
                            PhoneVerified = true
                        },
                        new
                        {
                            UserId = 3,
                            AccountStatus = "active",
                            CreatedAt = new DateTime(2026, 6, 8, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "shop@bikemate.test",
                            EmailVerified = true,
                            FirstName = "Maya",
                            LastName = "ShopAdmin",
                            PasswordHash = "sha256:a109e36947ad56de1dca1cc49f0ef8ac9ad9a7b1aa0df41fb3c4cb73c1ff01ea",
                            PhoneNumber = "+639171234567",
                            PhoneVerified = true
                        },
                        new
                        {
                            UserId = 4,
                            AccountStatus = "active",
                            CreatedAt = new DateTime(2026, 6, 8, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "admin@bikemate.test",
                            EmailVerified = true,
                            FirstName = "Ana",
                            LastName = "Admin",
                            PasswordHash = "sha256:a109e36947ad56de1dca1cc49f0ef8ac9ad9a7b1aa0df41fb3c4cb73c1ff01ea",
                            PhoneNumber = "+639171234567",
                            PhoneVerified = true
                        });
                });

            modelBuilder.Entity("BikeMate.Core.Entities.UserAuthProvider", b =>
                {
                    b.Property<int>("AuthProviderId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AuthProviderId"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<string>("ProviderEmail")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("ProviderName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("ProviderSubject")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("AuthProviderId");

                    b.HasIndex("UserId");

                    b.HasIndex("ProviderName", "ProviderSubject")
                        .IsUnique()
                        .HasFilter("[ProviderSubject] IS NOT NULL");

                    b.ToTable("user_auth_providers", "dbo");
                });

            modelBuilder.Entity("BikeMate.Core.Entities.UserDeviceToken", b =>
                {
                    b.Property<int>("DeviceTokenId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DeviceTokenId"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<string>("DeviceToken")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Platform")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasDefaultValue("android");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("DeviceTokenId");

                    b.HasIndex("UserId");

                    b.ToTable("user_device_tokens", "dbo");
                });

            modelBuilder.Entity("BikeMate.Core.Entities.UserRole", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.Property<DateTime>("AssignedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("user_roles", "dbo");

                    b.HasData(
                        new
                        {
                            UserId = 1,
                            RoleId = 1,
                            AssignedAt = new DateTime(2026, 6, 8, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            UserId = 2,
                            RoleId = 2,
                            AssignedAt = new DateTime(2026, 6, 8, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            UserId = 3,
                            RoleId = 3,
                            AssignedAt = new DateTime(2026, 6, 8, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            UserId = 4,
                            RoleId = 4,
                            AssignedAt = new DateTime(2026, 6, 8, 0, 0, 0, 0, DateTimeKind.Utc)
                        });
                });

            modelBuilder.Entity("BikeMate.Core.Entities.AuditLog", b =>
                {
                    b.HasOne("BikeMate.Core.Entities.User", "ActorUser")
                        .WithMany()
                        .HasForeignKey("ActorUserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("ActorUser");
                });

            modelBuilder.Entity("BikeMate.Core.Entities.Client", b =>
                {
                    b.HasOne("BikeMate.Core.Entities.User", "User")
                        .WithOne("Client")
                        .HasForeignKey("BikeMate.Core.Entities.Client", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("BikeMate.Core.Entities.ClientAddress", b =>
                {
                    b.HasOne("BikeMate.Core.Entities.Client", "Client")
                        .WithMany("Addresses")
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Client");
                });

            modelBuilder.Entity("BikeMate.Core.Entities.Conversation", b =>
                {
                    b.HasOne("BikeMate.Core.Entities.ServiceRequest", "Request")
                        .WithMany()
                        .HasForeignKey("RequestId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Request");
                });

            modelBuilder.Entity("BikeMate.Core.Entities.ConversationParticipant", b =>
                {
                    b.HasOne("BikeMate.Core.Entities.Conversation", "Conversation")
                        .WithMany("Participants")
                        .HasForeignKey("ConversationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BikeMate.Core.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Conversation");

                    b.Navigation("User");
                });

            modelBuilder.Entity("BikeMate.Core.Entities.LiveLocation", b =>
                {
                    b.HasOne("BikeMate.Core.Entities.Mechanic", "Mechanic")
                        .WithMany("LiveLocations")
                        .HasForeignKey("MechanicId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("BikeMate.Core.Entities.ServiceRequest", "Request")
                        .WithMany("LiveLocations")
                        .HasForeignKey("RequestId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Mechanic");

                    b.Navigation("Request");
                });

            modelBuilder.Entity("BikeMate.Core.Entities.Mechanic", b =>
                {
                    b.HasOne("BikeMate.Core.Entities.User", "User")
                        .WithOne("Mechanic")
                        .HasForeignKey("BikeMate.Core.Entities.Mechanic", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("BikeMate.Core.Entities.MechanicAvailability", b =>
                {
                    b.HasOne("BikeMate.Core.Entities.Mechanic", "Mechanic")
                        .WithMany("Availability")
                        .HasForeignKey("MechanicId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Mechanic");
                });

            modelBuilder.Entity("BikeMate.Core.Entities.Message", b =>
                {
                    b.HasOne("BikeMate.Core.Entities.Conversation", "Conversation")
                        .WithMany("Messages")
                        .HasForeignKey("ConversationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BikeMate.Core.Entities.User", "Sender")
                        .WithMany()
                        .HasForeignKey("SenderUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Conversation");

                    b.Navigation("Sender");
                });

            modelBuilder.Entity("BikeMate.Core.Entities.Motorcycle", b =>
                {
                    b.HasOne("BikeMate.Core.Entities.Client", "Client")
                        .WithMany("Motorcycles")
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Client");
                });

            modelBuilder.Entity("BikeMate.Core.Entities.Notification", b =>
                {
                    b.HasOne("BikeMate.Core.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("BikeMate.Core.Entities.OtpVerification", b =>
                {
                    b.HasOne("BikeMate.Core.Entities.User", "User")
                        .WithMany("OtpVerifications")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("BikeMate.Core.Entities.PasswordResetToken", b =>
                {
                    b.HasOne("BikeMate.Core.Entities.User", "User")
                        .WithMany("PasswordResetTokens")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("BikeMate.Core.Entities.Payment", b =>
                {
                    b.HasOne("BikeMate.Core.Entities.Client", "Client")
                        .WithMany("Payments")
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BikeMate.Core.Entities.PaymentMethod", "PaymentMethod")
                        .WithMany("Payments")
                        .HasForeignKey("PaymentMethodId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("BikeMate.Core.Entities.PaymentStatus", "PaymentStatus")
                        .WithMany("Payments")
                        .HasForeignKey("PaymentStatusId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BikeMate.Core.Entities.ServiceRequest", "Request")
                        .WithMany("Payments")
                        .HasForeignKey("RequestId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Client");

                    b.Navigation("PaymentMethod");

                    b.Navigation("PaymentStatus");

                    b.Navigation("Request");
                });

            modelBuilder.Entity("BikeMate.Core.Entities.PaymentEvent", b =>
                {
                    b.HasOne("BikeMate.Core.Entities.Payment", "Payment")
                        .WithMany("Events")
                        .HasForeignKey("PaymentId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Payment");
                });

            modelBuilder.Entity("BikeMate.Core.Entities.Product", b =>
                {
                    b.HasOne("BikeMate.Core.Entities.Shop", "Shop")
                        .WithMany("Products")
                        .HasForeignKey("ShopId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Shop");
                });

            modelBuilder.Entity("BikeMate.Core.Entities.ProductImage", b =>
                {
                    b.HasOne("BikeMate.Core.Entities.Product", "Product")
                        .WithMany("Images")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("BikeMate.Core.Entities.RequestMedia", b =>
                {
                    b.HasOne("BikeMate.Core.Entities.ServiceRequest", "Request")
                        .WithMany("Media")
                        .HasForeignKey("RequestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Request");
                });

            modelBuilder.Entity("BikeMate.Core.Entities.RequestStatusHistory", b =>
                {
                    b.HasOne("BikeMate.Core.Entities.User", "ChangedByUser")
                        .WithMany()
                        .HasForeignKey("ChangedByUserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("BikeMate.Core.Entities.RequestStatus", "NewStatus")
                        .WithMany()
                        .HasForeignKey("NewStatusId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BikeMate.Core.Entities.RequestStatus", "OldStatus")
                        .WithMany()
                        .HasForeignKey("OldStatusId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("BikeMate.Core.Entities.ServiceRequest", "Request")
                        .WithMany("StatusHistory")
                        .HasForeignKey("RequestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ChangedByUser");

                    b.Navigation("NewStatus");

                    b.Navigation("OldStatus");

                    b.Navigation("Request");
                });

            modelBuilder.Entity("BikeMate.Core.Entities.Review", b =>
                {
                    b.HasOne("BikeMate.Core.Entities.Client", "Client")
                        .WithMany()
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BikeMate.Core.Entities.Mechanic", "Mechanic")
                        .WithMany("Reviews")
                        .HasForeignKey("MechanicId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BikeMate.Core.Entities.ServiceRequest", "Request")
                        .WithOne("Review")
                        .HasForeignKey("BikeMate.Core.Entities.Review", "RequestId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Client");

                    b.Navigation("Mechanic");

                    b.Navigation("Request");
                });

            modelBuilder.Entity("BikeMate.Core.Entities.ServiceImage", b =>
                {
                    b.HasOne("BikeMate.Core.Entities.ShopService", "ShopService")
                        .WithMany("Images")
                        .HasForeignKey("ShopServiceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ShopService");
                });

            modelBuilder.Entity("BikeMate.Core.Entities.ServiceRequest", b =>
                {
                    b.HasOne("BikeMate.Core.Entities.Client", "Client")
                        .WithMany("ServiceRequests")
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BikeMate.Core.Entities.RequestStatus", "CurrentStatus")
                        .WithMany("ServiceRequests")
                        .HasForeignKey("CurrentStatusId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BikeMate.Core.Entities.Mechanic", "Mechanic")
                        .WithMany("AssignedRequests")
                        .HasForeignKey("MechanicId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("BikeMate.Core.Entities.Motorcycle", "Motorcycle")
                        .WithMany()
                        .HasForeignKey("MotorcycleId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("BikeMate.Core.Entities.Shop", "Shop")
                        .WithMany("ServiceRequests")
                        .HasForeignKey("ShopId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("BikeMate.Core.Entities.ShopService", "ShopService")
                        .WithMany("ServiceRequests")
                        .HasForeignKey("ShopServiceId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Client");

                    b.Navigation("CurrentStatus");

                    b.Navigation("Mechanic");

                    b.Navigation("Motorcycle");

                    b.Navigation("Shop");

                    b.Navigation("ShopService");
                });

            modelBuilder.Entity("BikeMate.Core.Entities.Shop", b =>
                {
                    b.HasOne("BikeMate.Core.Entities.User", "Owner")
                        .WithMany("OwnedShops")
                        .HasForeignKey("OwnerUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Owner");
                });

            modelBuilder.Entity("BikeMate.Core.Entities.ShopMechanic", b =>
                {
                    b.HasOne("BikeMate.Core.Entities.Mechanic", "Mechanic")
                        .WithMany("ShopMechanics")
                        .HasForeignKey("MechanicId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BikeMate.Core.Entities.Shop", "Shop")
                        .WithMany("ShopMechanics")
                        .HasForeignKey("ShopId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Mechanic");

                    b.Navigation("Shop");
                });

            modelBuilder.Entity("BikeMate.Core.Entities.ShopOperatingHour", b =>
                {
                    b.HasOne("BikeMate.Core.Entities.Shop", "Shop")
                        .WithMany("OperatingHours")
                        .HasForeignKey("ShopId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Shop");
                });

            modelBuilder.Entity("BikeMate.Core.Entities.ShopService", b =>
                {
                    b.HasOne("BikeMate.Core.Entities.ServiceCategory", "Category")
                        .WithMany("ShopServices")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BikeMate.Core.Entities.Shop", "Shop")
                        .WithMany("Services")
                        .HasForeignKey("ShopId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("Shop");
                });

            modelBuilder.Entity("BikeMate.Core.Entities.UserAuthProvider", b =>
                {
                    b.HasOne("BikeMate.Core.Entities.User", "User")
                        .WithMany("AuthProviders")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("BikeMate.Core.Entities.UserDeviceToken", b =>
                {
                    b.HasOne("BikeMate.Core.Entities.User", "User")
                        .WithMany("DeviceTokens")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("BikeMate.Core.Entities.UserRole", b =>
                {
                    b.HasOne("BikeMate.Core.Entities.Role", "Role")
                        .WithMany("UserRoles")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BikeMate.Core.Entities.User", "User")
                        .WithMany("UserRoles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");

                    b.Navigation("User");
                });

            modelBuilder.Entity("BikeMate.Core.Entities.Client", b =>
                {
                    b.Navigation("Addresses");

                    b.Navigation("Motorcycles");

                    b.Navigation("Payments");

                    b.Navigation("ServiceRequests");
                });

            modelBuilder.Entity("BikeMate.Core.Entities.Conversation", b =>
                {
                    b.Navigation("Messages");

                    b.Navigation("Participants");
                });

            modelBuilder.Entity("BikeMate.Core.Entities.Mechanic", b =>
                {
                    b.Navigation("AssignedRequests");

                    b.Navigation("Availability");

                    b.Navigation("LiveLocations");

                    b.Navigation("Reviews");

                    b.Navigation("ShopMechanics");
                });

            modelBuilder.Entity("BikeMate.Core.Entities.Payment", b =>
                {
                    b.Navigation("Events");
                });

            modelBuilder.Entity("BikeMate.Core.Entities.PaymentMethod", b =>
                {
                    b.Navigation("Payments");
                });

            modelBuilder.Entity("BikeMate.Core.Entities.PaymentStatus", b =>
                {
                    b.Navigation("Payments");
                });

            modelBuilder.Entity("BikeMate.Core.Entities.Product", b =>
                {
                    b.Navigation("Images");
                });

            modelBuilder.Entity("BikeMate.Core.Entities.RequestStatus", b =>
                {
                    b.Navigation("ServiceRequests");
                });

            modelBuilder.Entity("BikeMate.Core.Entities.Role", b =>
                {
                    b.Navigation("UserRoles");
                });

            modelBuilder.Entity("BikeMate.Core.Entities.ServiceCategory", b =>
                {
                    b.Navigation("ShopServices");
                });

            modelBuilder.Entity("BikeMate.Core.Entities.ServiceRequest", b =>
                {
                    b.Navigation("LiveLocations");

                    b.Navigation("Media");

                    b.Navigation("Payments");

                    b.Navigation("Review");

                    b.Navigation("StatusHistory");
                });

            modelBuilder.Entity("BikeMate.Core.Entities.Shop", b =>
                {
                    b.Navigation("OperatingHours");

                    b.Navigation("Products");

                    b.Navigation("ServiceRequests");

                    b.Navigation("Services");

                    b.Navigation("ShopMechanics");
                });

            modelBuilder.Entity("BikeMate.Core.Entities.ShopService", b =>
                {
                    b.Navigation("Images");

                    b.Navigation("ServiceRequests");
                });

            modelBuilder.Entity("BikeMate.Core.Entities.User", b =>
                {
                    b.Navigation("AuthProviders");

                    b.Navigation("Client");

                    b.Navigation("DeviceTokens");

                    b.Navigation("Mechanic");

                    b.Navigation("OtpVerifications");

                    b.Navigation("OwnedShops");

                    b.Navigation("PasswordResetTokens");

                    b.Navigation("UserRoles");
                });
#pragma warning restore 612, 618
        }
    }
}
